using HangmanGame.BusinessLogic;
using HangmanGame.DataAccess;
using System;
using System.Linq;

namespace HangmanGame.Presentation
{
    // დავალება # 3 - ჩამოხრჩობანა

    // ამ თამაშში პროგრამამ უნდა აირჩიოს შემთხვევითი სიტყვა წინასწარ გამზადებული სიტყვების List - იდან, შეგიძლიათ გამოიყენოთ ეს ლისტი.

    //         List<string> words = new List<string>
    //         {
    //             "apple", "banana", "orange", "grape", "kiwi",
    //             "strawberry", "pineapple", "blueberry", "peach", "watermelon"
    //         };

    // მომხმარებელს უნდა ჰქონდეს 6 - ჯერ ასოს გახსნის საშუალება, 
    // თუ ასეთი ასო სიტყვაში ფიგურირებს უნდა გამოჩნდეს თუ რომელ პოზიციაზეა არსებული ასო.
    // ამის შემდეგ მომხმარებელმა უნდა შეიყვანოს სრულად სიტყვის დასახელება, თუ შეყვანილი სიტყვა დაემთხვა მოსაძებნ სიტყვას მომხმარებელი იგებს, 
    // წინააღმდეგ შემთხვევაში მარცხდება.
    // თუ მომხმარებელმა ექვსივეჯერ ისეთი ასო შეიყვანა რომელიც სიტყვაში საერთოდ არ ფიგურირებს მომხმარებელი უნდა დამარცხდეს.
    // თუ მომხმარებელმა ექვსი ასოს შეყვანისას სიტყვაში არსებული ყველა ასო გახსნა და გამოიცნო მომხმარებელი იმარჯვებს.



    // მომხმარებლის თამაშების ისტორია უნდა ინახებოდეს XML ფორმატში მის სახელთან და უმაღლეს ქულასთან ერთად, 
    // რათა მომხმარებელმა შეძლოს TOP 10 მოთამაშის და მისი შედეგების ნახვა და რეკორდების გაუმჯობესება.
    class Program
    {
        private readonly GameEngine _gameEngine;
        private readonly ScoreManager _scoreManager;

        public Program()
        {
            var dataService = new XmlDataService();
            _scoreManager = new ScoreManager(dataService);
            _gameEngine = new GameEngine();
        }

        static void Main(string[] args)
        {
            var program = new Program();
            program.DisplayMenu();
        }

        private void DisplayMenu()
        {
            string choice;
            do
            {
                Console.WriteLine("HANGMAN GAME");
                Console.WriteLine("1. NewGame");
                Console.WriteLine("2. TOP 10 score");
                Console.WriteLine("3. Exict");
                Console.Write("\nChoose: ");

                choice = Console.ReadLine();

                switch (choice)
                {
                    case "1":
                        RunGame();
                        break;
                    case "2":
                        DisplayTopScores();
                        break;
                    case "3":
                        Console.WriteLine("Thanks for playing! Goodbye.");
                        break;
                    default:
                        Console.WriteLine("Invalid selection. Please try again.");
                        break;
                }

                if (choice != "3")
                {
                    Console.WriteLine("\nPress any button to return to the menu...");
                    Console.ReadKey();
                }

            } while (choice != "3");
        }

        private void RunGame()
        {
            _gameEngine.StartNewGame();

            while (!_gameEngine.IsGameOver && _gameEngine.GuessesLeft > 0)
            {
                DisplayStatus();
                Console.Write("\nEnter a letter or full word: ");
                string input = Console.ReadLine()?.ToLower().Trim();

                if (string.IsNullOrEmpty(input)) continue;

                if (input.Length == 1 && char.IsLetter(input[0]))
                {
                    _gameEngine.GuessLetter(input[0]);
                }
                else if (input.Length > 1)
                {
                    _gameEngine.GuessWord(input);
                    break;
                }
                else
                {
                    Console.WriteLine("Please enter only one letter (A-Z) or a complete word.");
                    Thread.Sleep(1000);
                }
            }

            if (_gameEngine.IsGameOver)
            {
                DisplayFinalResult();
            }
        }

        private async void DisplayTopScores()
        {
            List<PlayerScore> topScores = await _scoreManager.GetTopScores(10);

            Console.WriteLine("TOP 10 SCORE");

            if (!topScores.Any())
            {
                Console.WriteLine("\nNo scores saved yet. Play and set a record!");
                return;
            }

            for (int i = 0; i < topScores.Count; i++)
            {
                var score = topScores[i];
                Console.WriteLine($"{i + 1,-3} {score.Name,-25} {score.HighScore,5}");//Generated by AI
            }
        }
        #region HELPERS
        private void DisplayStatus()
        {
            Console.WriteLine($"Guess Left: {_gameEngine.GuessesLeft} / {_gameEngine.MaxGuesses}");

            Console.WriteLine($"\nWord: {_gameEngine.GetDisplayWord()}");

            if (!string.IsNullOrEmpty(_gameEngine.GetIncorrectGuesses()))
            {
                Console.WriteLine($"\nIncorrect guesses: [ {_gameEngine.GetIncorrectGuesses()} ]");
            }
        }

        private void DisplayFinalResult()
        {
            Console.WriteLine($"Target word: ** {_gameEngine.GetTargetWord().ToUpper()}");

            if (_gameEngine.DidWin)
            {
                int score = _gameEngine.CalculateScore();
                Console.WriteLine("Congratulation! You Won!");
                Console.WriteLine($"Your Score: {score}");

                Console.Write("\nEnter your name to save score: ");
                string playerName = Console.ReadLine();
                _scoreManager.SaveScore(playerName, score);
            }
            else
            {
                Console.WriteLine("You Lose ... Try again!");
                Console.WriteLine("Your score: 0");
            }
        }
        #endregion
    }
}